In [1]:
import torch

In [5]:
def matmul(a, b):
    D1, D2 = a.shape
    D3, D4 = b.shape
    if D2 != D3:
        raise Exception("Matrix shapes don't align")

    a = a.view(D1, D2, 1)
    b = b.view(1, D3, D4)
    return (a * b).sum(dim=1)



In [10]:
testm = torch.rand(5,5)
matmul(2*torch.eye(5), testm) == 2*testm

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [12]:
memes = torch.rand((3,5))
memes

tensor([[0.3305, 0.4960, 0.9375, 0.1740, 0.6060],
        [0.6064, 0.8238, 0.4918, 0.3108, 0.0745],
        [0.8108, 0.5421, 0.7323, 0.5002, 0.1726]])

In [14]:
torch.randperm(5)

tensor([3, 1, 4, 0, 2])

In [22]:
torch.rand((4,3,5)).argsort(dim=1)

tensor([[[1, 1, 2, 0, 1],
         [0, 0, 0, 2, 0],
         [2, 2, 1, 1, 2]],

        [[0, 1, 0, 1, 0],
         [1, 2, 2, 2, 2],
         [2, 0, 1, 0, 1]],

        [[2, 0, 2, 1, 1],
         [0, 2, 0, 2, 2],
         [1, 1, 1, 0, 0]],

        [[2, 2, 1, 2, 0],
         [0, 0, 2, 1, 1],
         [1, 1, 0, 0, 2]]])

In [25]:
torch.randint(0, 3, (4,1,5)), torch.randint(0, 2, (4,1,5))

(tensor([[[0, 1, 1, 1, 2]],
 
         [[2, 0, 2, 1, 2]],
 
         [[1, 1, 0, 1, 2]],
 
         [[2, 1, 1, 1, 0]]]),
 tensor([[[1, 1, 0, 1, 0]],
 
         [[1, 1, 0, 0, 1]],
 
         [[1, 0, 1, 1, 0]],
 
         [[1, 1, 1, 1, 0]]]))

In [29]:
def randpair_idx(xs, dim):
    n = xs.shape[dim]
    if n < 2: 
        raise Exception("Dimension not large enough.")
    shape = xs.shape
    shape[dim] = 1
    p1 = torch.randint(0, n, shape)
    p2 = torch.randint(1, n, shape)
    p2 = (p1 + p2) % n
    torch.cat((p1, p2), dim=n)

tensor([[[1, 0, 2, 2, 2],
         [0, 2, 0, 0, 0]],

        [[1, 2, 1, 1, 1],
         [2, 0, 2, 0, 0]],

        [[2, 2, 0, 1, 0],
         [0, 1, 2, 0, 1]],

        [[0, 0, 1, 2, 0],
         [2, 1, 0, 0, 2]]])

In [35]:
a = torch.rand((2,2))
a

tensor([[0.9987, 0.6983],
        [0.3286, 0.1695]])

In [45]:
b = torch.zeros((2, 2), dtype=bool)
b[0,1] = True
b[1,0] = True
b

tensor([[False,  True],
        [ True, False]])

In [47]:
a[b].view(2,1)

tensor([[0.6983],
        [0.3286]])

In [125]:
idxs = torch.rand((2,2)).argsort(dim=1)
idxs

tensor([[1, 0],
        [0, 1]])

In [126]:
offset = torch.arange(2).view(2,1).tile((1,2)) * 2

In [127]:
idxs_ = (idxs + offset).view(-1)

In [128]:
a = torch.tensor([[1,2], [3,4]])

In [129]:
a.view(-1)[idxs_].view(2,2)

tensor([[2, 1],
        [3, 4]])

In [132]:
dims = torch.arange(0, 2)
dims[0] = 1
dims[1] = 0
dims = tuple([i.item() for i in dims])
dims

(1, 0)

In [141]:
product(a.shape[:-1])

NameError: name 'prod' is not defined

In [207]:
def shuffle_dim(xs, dim):
    """Permutes elements along a dimension."""
    xs_ = xs.transpose(dim, -1)
    perms = torch.rand(xs_.shape).argsort(dim=-1)
    perm_size = xs_.shape[-1]
    perms = perms.view(-1, perm_size)
    offset = torch.arange(perms.shape[0]).unsqueeze(-1).tile(1, perm_size) * perm_size
    idxs = (perms + offset).view(-1)
    return (xs_.reshape(-1)[idxs]).view(xs_.shape).transpose(dim, -1)
    


In [208]:
shuffle_dim(torch.tensor([[[0,1],[2,3]],[[4,5],[6,7]]]), dim=0)

tensor([[[4, 1],
         [2, 3]],

        [[0, 5],
         [6, 7]]])

In [225]:
xs = torch.rand((2,11))
xs

tensor([[0.0895, 0.9450, 0.3521, 0.2885, 0.9661, 0.4657, 0.0403, 0.5291, 0.6579,
         0.3212, 0.7341],
        [0.4194, 0.4785, 0.8703, 0.5265, 0.8987, 0.7996, 0.4284, 0.1319, 0.1669,
         0.3937, 0.6029]])

In [228]:
xs_ = xs[:,:-1].reshape(2,5,2)
xs_

tensor([[[0.0895, 0.9450],
         [0.3521, 0.2885],
         [0.9661, 0.4657],
         [0.0403, 0.5291],
         [0.6579, 0.3212]],

        [[0.4194, 0.4785],
         [0.8703, 0.5265],
         [0.8987, 0.7996],
         [0.4284, 0.1319],
         [0.1669, 0.3937]]])

In [238]:
torch.cat((xs_[:,:,0] + xs_[:,:,1], xs[:,-1].unsqueeze(-1)), dim=-1)

tensor([[1.0345, 0.6406, 1.4319, 0.5694, 0.9791, 0.7341],
        [0.8979, 1.3969, 1.6983, 0.5603, 0.5607, 0.6029]])

In [241]:
slices = [slice(None, None) for _ in range(2)]
key_0 = tuple(slices + [0])
key_1 = tuple(slices + [1])
torch.cat((xs_[key_0] + xs_[key_1], xs[:,-1].unsqueeze(-1)), dim=-1)

tensor([[1.0345, 0.6406, 1.4319, 0.5694, 0.9791, 0.7341],
        [0.8979, 1.3969, 1.6983, 0.5603, 0.5607, 0.6029]])

In [248]:
def recursive_binop(xs, binop, dim):

    no_dims = len(xs.shape)
    slices = [slice(None, None) for _ in range(no_dims)]
    key_0 = tuple(slices + [0])
    key_1 = tuple(slices + [1])
    key_ltn1 = tuple(slices[:-1] + [slice(None, -1)])
    key_n1 = tuple(slices[:-1] + [-1])

    def rec(xs):
        size = xs.shape[-1]
        if size % 2 == 0:
            xs = xs.reshape(*xs.shape[:-1], size // 2, 2)
            return binop(xs[key_0], xs[key_1])
        else:
            xs_ = xs[key_ltn1]
            xs_ = xs_.reshape(*xs.shape[:-1], size // 2, 2)
            print(xs_)
            return torch.cat((binop(xs[key_0], xs[key_1]), xs[key_n1.unsqueeze(-1)]), dim=-1)
            
    return rec(xs.transpose(dim, -1)).transpose(dim, -1)


In [249]:
recursive_binop(torch.arange(0,5), lambda a, b: a + b, dim=0)

IndexError: too many indices for tensor of dimension 1